#!/bin/bash

#$ -P bf528
#$ -cwd
#$ -pe omp 16
#$ -o /projectnb/bf528/users/dreadlocks/project_5/sarah/run_fc_o
#$ -e /projectnb/bf528/users/dreadlocks/project_5/sarah/run_fc_e

source /etc/bashrc

module load anaconda3
conda activate pj5_env

GTF=/project/bf528/project_3/reference/rn4_refGene_20180308.gtf
OUT=/projectnb/bf528/users/dreadlocks/project_5/sarah/feature
NAME=$(basename "$1".txt)

featureCounts -p -T 16 -a $GTF -o $OUT/$NAME $1